main: main.o applicationLayer.o DataLink.o
	gcc -o main main.o applicationLayer.o DataLink.o

main.o: main.c
	gcc -c main.c

applicationLayer.o: applicationLayer.c
	gcc -c applicationLayer.c

DataLink.o: DataLink.c
	gcc -c DataLink.c


